steps:
  # --- API (NestJS) ---
  - name: gcr.io/cloud-builders/docker
    id: Build API Image
    dir: ats-service
    args: [ "build", "-t", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_API}:${COMMIT_SHA}", "-f", "Dockerfile", "." ]
  - name: gcr.io/cloud-builders/docker
    id: Push API Image
    args: [ "push", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_API}:${COMMIT_SHA}" ]
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Deploy API to Cloud Run
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_API}
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_API}:${COMMIT_SHA}
      - --region=${_REGION}
      - --platform=${_PLATFORM}

  # --- WEB (Angular) ---
  - name: gcr.io/cloud-builders/docker
    id: Build Web Image
    dir: ats-ui
    args: [ "build", "-t", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_WEB}:${COMMIT_SHA}", "-f", "Dockerfile", "." ]
  - name: gcr.io/cloud-builders/docker
    id: Push Web Image
    args: [ "push", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_WEB}:${COMMIT_SHA}" ]
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Deploy Web to Cloud Run
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_WEB}
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_WEB}:${COMMIT_SHA}
      - --region=${_REGION}
      - --platform=${_PLATFORM}

options:
  logging: CLOUD_LOGGING_ONLY
